### ISSUE TITLE
AndroidStudio cannot resolve synthetic property of Kotlin Android Extensions

### ISSUE THREAD

**Issue by PhilippBurgk** [gradle/kotlin-dsl#377]
I'm trying to use Gradle Kotlin script in my Android project and I have a problem. AndroidStudio 2.3.2 cannot resolve the synthetic properties of Kotlin Android Extensions. The problem also exists in the sample hello-android project. You need the following changes.

- Apply the plugin
`plugin("kotlin-android-extensions")`
- Add an Id to the TextView inside activity_main.xml
`android:id="@+id/testId"`
- Change the directory from src/main/kotlin to src/main/java
- Import the synthetic properties in the `MainActivity `
`import kotlinx.android.synthetic.main.activity_main.*`
- Add the following line at the end of the `onCreate` method
`testId`

Gradle works and I can run the App on a device. Only AndroidStudio has a problem.
<img width="403" alt="kotlin-android-extensions" src="https://cloud.githubusercontent.com/assets/28691674/26539460/d22d7d22-444c-11e7-97eb-c080cb068ec7.png">

**Comment by GFriedrich** [comment]
Having the same issue.
Seems that the "extensions" compiler plugin is not recognized properly by the IDE when applying it via Gradle/Kotlin build script.

**Comment by GFriedrich** [comment]
@bamboo this can be closed now - it's working fine with Kotlin 1.1.4 - just tested it.

**Comment by bamboo** [comment]
Thanks, @GFriedrich.

We've just upgraded to Kotlin 1.1.4 as well (see #414).

**Comment by mradzinski** [comment]
Still an issue using Kotlin 1.1.4-2...

**Comment by GFriedrich** [comment]
@mradzinski did you make sure to update the Kotlin plugin of the IDE? Only updating the dependency is not enough.

**Comment by mradzinski** [comment]
I managed to make it work. The problem was that *Configure Kotlin in project* tool was adding just the `Kotlin` plugin and not the `Kotlin-android` one too, so I was just adding `kotlin-android-extensions` without having the `Kotlin-android` one.

**Comment by jaredsburrows** [comment]
This still does not work for me with Intellij `2017.2.2` and Kotlin `1.1.4-2`.

**Comment by jaredsburrows** [comment]
After doing the following, it seems to work!
- `File | Invalidate Caches / Restart`
- Deleting `.idea` folder
- Running `gradlew clean`
- Re-import the project

**Comment by avonil** [comment]
I just removed apply plugin: 'kotlin-android-extensions' , synchronize gradle plugin and then I added it again.

**Comment by adrian110288** [comment]
@avonil worked like a charm!

**Comment by autonomousapps** [comment]
Android Studio 3.1.2 randomly decides it can't resolve these synthetic references, even though the app builds fine. A rebuild always fixes the erroneous IDE error, but just now I observed that the error "went away" only to return less than a minute later without me even interacting with my IDE. This is bizarre. Anyone know where I can file a bug report? Probably Android Studio-related, not Kotlinx-related....

**Comment by carlosefonseca** [comment]
@autonomousapps I have a layout file called "aaaaa.xml" and I just rename it adding or removing an 'a'. This is enough for Android Studio to re-index or whatever and clear the errors… But I'm getting really tired of doing it. And I don't really know if it's plugin or IDE's fault…

**Comment by autonomousapps** [comment]
@carlosefonseca et al, I filed an official bug report on this issue a couple weeks ago. Feel free to star it to let Google know how much you care :) https://issuetracker.google.com/issues/80089849

**Comment by wahibhaq** [comment]
This is really annoying problem. I am using the latest `kotlin-gradle-plugin` and still couldn't find a more pragmatic way to resolve this. 

For now seems like solution shared by @dkwasniak worked for me. Thanks to those who have reported bug reports.

**Comment by zloyreznic** [comment]
https://youtrack.jetbrains.com/issue/KT-23908

**Comment by mnewlive** [comment]
i used ext.kotlin_version = '1.2.50' and after this clean and rebuild the project.

**Comment by mhsmith** [comment]
There are responses from Google at https://issuetracker.google.com/issues/78547457:

Jun 15, 2018 07:40PM 
We are working with JetBrains on a fix. We have already sent a proposed patch, and we'll integrate it in Studio shortly. And yes, it seems to have started with Kotlin 1.2.40.

Jul 6, 2018 12:16AM 
This should now be fixed by Kotlin 1.2.51, but I'll keep the bug open just in case we get more reports of it happening even after the update.

(Multiple users responded that the bug still occurs with Kotlin 1.2.51.)

Aug 8, 2018 08:22PM 
This should be fixed in upcoming 3.2 RC1. We'll re-open if we get reports of this still showing up in 3.2 RCs or 3.3.

**Comment by nokite** [comment]
3.2.1 - IDE still shows errors. 
This started happening after I enabled androidExtensions {experimental = true}.
Eventually the build succeeds, but the errors persist in the IDE.
Kotlin 1.3

**Comment by techinsight** [comment]
Now so many layouts, drawables. etc. Split layout in res_* name format folders.
The problem is synthetic cannot resolve the layouts in those resource folders.
Any solutions!!??

**Comment by techinsight** [comment]
> Now so many layouts, drawables. etc. Split layout in res_* name format folders.
> The problem is synthetic cannot resolve the layouts in those resource folders.
> Any solutions!!??

synthetic just resolve layouts in res name folder.

**Comment by SrHalf** [comment]
I'm getting the same error persistently! Nothing fixes it. 

BUILD.GRADLE PROJECT:
`buildscript {`
`//`
    `ext.kotlin_version = '1.3.11'`
`//`
    `dependencies {`
        `classpath 'com.android.tools.build:gradle:3.2.1'`
        `classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"`
        `classpath 'com.google.gms:google-services:4.2.0'`
`//`

BUILD.GRADLE MODULE:
`apply plugin: 'com.android.application'`
`apply plugin: 'kotlin-android'`
`apply plugin: 'kotlin-android-extensions'`
`//`
`dependencies {`
    `implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"`
`//`

And my imports keep showing:
`Unresolved reference: app`
`Unresolved reference: widget`
`Unused import directive` (kotlinx)

**Comment by wangchunlei000** [comment]
So ,what is the solution?? I have the same error!

**Comment by gefilte** [comment]
I just posted a bug (since Google closed the old bug, even though the problem persists!) with root cause. I also included a temporary workaround.  See: https://issuetracker.google.com/issues/145888144

**Comment by oshetima** [comment]
I tried everything possible and nothing worked. The only solution for me was to delete .AndroidStudio folder from C:/Users/YourName/. Android Studio resets and everything works as it should.

**Comment by RahulSDeshpande** [comment]
For me it is working for `Activity` but not for `Fragment`s!!
How strange is this!! 💩

**Comment by SrHalf** [comment]
I've solved this clicking on: Files>>Invalidate caches and restart. (Or something like that😅).

**Comment by gurelliali** [comment]
I try every other solution bu no one worked for me. At the and I cloned project again and now it's working. I love android studio 👯
